//
// Created by wei xiang on 2023/6/28.
//


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef DORIS_SEGMENT_BUILDER_JNI_H
#define DORIS_SEGMENT_BUILDER_JNI_H

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniExample
 * Method:    segmentBuild
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_JniExample_segmentBuild
        (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}

#endif //DORIS_SEGMENT_BUILDER_JNI_H



/* Header for class JniExample */

#ifndef _Included_JniExample
#define _Included_JniExample

#endif
#endif
